site_name: ED3N Hydro Boards
site_url: https://cajun1689.github.io/ed3n/
repo_url: https://github.com/cajun1689/ed3n

theme:
  name: material
  palette:
    scheme: slate     # dark mode
    primary: teal
  logo: images/ed3n-logo.svg        # relative to docs/
  favicon: images/ed3n-logo.svg

plugins:
  - search            # only the built-in search plugin

nav:
  - Home: index.md

  - Boards:
      - Hydro Lite: boards/hydro-lite.md
      - Hydro: boards/hydro.md
      - Hydro Pro: boards/hydro-pro.md

  - Tested Accessories: tested-accessories.md
  - Tested Software: tested-software.md
